### ISSUE TITLE
[Closed] Font Size Wont Change

### ISSUE THREAD

**Issue by brodycritchlow** [BatDev0/htmlwebsite#4]
Hello! 
I added a classed div, and went to change they font size. And they font-size wont change to 32px, Is this because i have an h1 span over it and setting that font size? Or is it something else

**Comment by brodycritchlow** [comment]
@dcritchlow Also when it does work its way too big and takes up the whole space

**Comment by dcritchlow** [comment]
Ok I will look at it

**Comment by dcritchlow** [comment]
What font size do you want?

**Comment by brodycritchlow** [comment]
Never mind it was because of the main class setting the font i had to add two divs

**Comment by brodycritchlow** [comment]
close #4
